// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "prisma/config";
import dotenv from "dotenv";
dotenv.config({ path: "./.env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
    // @ts-expect-error - directUrl is supported in runtime but types might be missing
    directUrl: env("DIRECT_URL"),
  },
});
